# Updates workflows from the "template" repo.

name: Sync workflows

on:
  workflow_dispatch: ~

jobs:
  update-workflows:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          path: 'repo'
      - name: Checkout template
        uses: actions/checkout@v4
        with:
          repository: 'Snapkg/template'
          path: 'template'
      - name: Update workflows
        run: "rm -rf ./repo/.github && mkdir -p ./repo/.github/workflows && cp -rf ./template/.github/workflows ./repo/.github"
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Synced workflows from template repo"
          repository: 'repo'
      - name: test
        run: "ls ./repo/.github/workflows"
