# Updates workflows from the "template" repo.

name: Update workflows

on:
  workflow_dispatch: ~

jobs:
  update-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          path: 'repo'
      - name: Checkout template
        uses: actions/checkout@v4
        with:
          repository: 'Snapkg/template'
          path: 'template'
      - name: Update workflows
        run: "mkdir ./repo/.github && mkdir ./repo/.github/workflows cp -rf ./template/.github/workflows ./repo/.github/workflows"
      - name: test
        run: "ls ./repo/.github/workflows"
